language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install -U .[test] zope.testrunner coverage
script:
    - coverage run -m zope.testrunner --test-path=src
notifications:
    email: false
